### ISSUE TITLE
01 example

### ISSUE THREAD

**Issue by jamesli2021** [MicroWebStacks/astro-examples#1]
Node version could not render on the page, it's blank due to CSS when using Dark Reader extension.

Tested on Astro 2.0.10 with Nodejs 18.14.0 but console.log can see version.

It's better to remove the styling to avoid problematic for users.

**Comment by wassfila** [comment]
Can you post a screenshot of the issue ?
Given that this is an example that focus on Astro usage pattern, it is not intended for final readers on the internet.
Nevertheless, if you have suggestions of improvements, let me know. Not using styles at all, is not the solution. Some sites I develop for real ise cases are even Dark only as basis e.g. https://astro.build/themes/details/astro-big-doc/

otherwise, the fix would be to offed dark/light mode on the website.

**Comment by wassfila** [comment]
out of scope to support Dark reader as in a real example Two themes should be offered, these are usage patterns to learn the framework and what keeps them simply is that each example focus on one problem at a time.
